BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Up'
            on_press: app.handle_increment(1)
        TextInput:
            id: input_miles
            text: ''
            on_text: app.handle_convert()
        Button:
            text: 'Down'
            on_press: app.handle_increment(-1)
    Label:
        text: app.result
        color: (1, 1, 0, 1)