BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
        Button:
            text: 'Square'
            on_press: app.handle_calculate()
        Label:
            id: output_label
            text: 'Result'
            color: (1, 0.75, 0.8, 1)
    Label:
        text: 'Enter a number and press "Square".'